### ISSUE TITLE
Playlists and Channels not adding

### ISSUE THREAD

**Issue by najchris11** [Tzahi12345/YoutubeDL-Material#244] opened 2020-11-10 14:47 UTC
Hi!
So I don't know if this is a result of the yt dl issue, but I can't seem to add playlists or channels.
These are my logs when entering the URLs:
`2020-11-10T14:38:30.195Z ERROR: Subscribe: Failed to get subscription info. Subscribe failed.`
Tried this a few times and reinstalled several times.

**Comment by Tzahi12345** [comment] 2020-11-11 07:12
Hello! Can you go into the advanced tab in the settings and try changing the downloader from youtube-dl to youtube-dlc? It could be that it's working with one and not the other.

**Comment by prismopensource** [comment] 2020-11-11 13:16
Have the exact same problem when trying to add subscriptions here. The advanced tab in the Settings dialog only let's me change the default downloading agent to, aria2c, avconv, axel, curl, ffmpeg, httpie or wget.

**Comment by WillsonHaw** [comment] 2020-11-11 18:12
It was an issue for both `youtube-dl` and `youtube-dlc` for me, both on the latest and on `nightly` via Docker

**Comment by Tzahi12345** [comment] 2020-11-12 00:32
@prismopensource Update to the latest nightly and you should see that option

@WillsonHaw thx for the info!

**Comment by bobingtion** [comment] 2020-11-12 04:26
i can confirm i am on nightly it download the video in the folder but it dose not show up to watch in the app the log is ERROR: p4xrvY2yiuM: YouTube said: Unable to extract video data it is youtubedl issue not the apps you can see here https://github.com/l1ving/youtube-dl/issues/20

**Comment by prismopensource** [comment] 2020-11-12 13:10
> @prismopensource Update to the latest nightly and you should see that option

Running docker image here, any chance that will be updated as well?

**Comment by bobingtion** [comment] 2020-11-13 01:37
@prismopensource when you pull the docker just add  :nightly  at the end

**Comment by Tzahi12345** [comment] 2020-11-14 08:04
Hm, so I just tried subscribing to a channel and I'm not seeing this error come up. I agree with @bobingtion that it's a problem youtube-dl side, once they (or youtube-dlc) updates to fix the issue, it should be fixed on our end (youtube-dl updates on server restart, though eventually I want to allow users to manually update from within the GUI as well).

I'll close this issue since there's nothing I can do from my end, but if you guys get more info feel free to include that here!

**Closed by Tzahi12345** 2020-11-14 08:04 UTC
Labels: bug
