### ISSUE TITLE
Adding UID and GID breaks docker container

### ISSUE THREAD

**Issue by tehniemer** [Tzahi12345/YoutubeDL-Material#373] opened 2021-04-24 01:30 UTC
I'm getting the following error on creation of a fresh Docker container if I use the `UID` and `GID` docker environment variables. If I comment them out it starts fine.

```
Error: Failed to create directory /.forever:EACCES: permission denied, mkdir '/.forever',
    at Module.load (internal/modules/cjs/loader.js:863:32),
    at Object.tryCreateDir (/usr/lib/node_modules/forever/lib/util/config-utils.js:22:11),
    at Object.forever.load (/usr/lib/node_modules/forever/lib/forever.js:357:15),
    at Object.<anonymous> (/usr/lib/node_modules/forever/lib/forever.js:391:9),
    at Module._compile (internal/modules/cjs/loader.js:999:30),
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10),
    at Function.Module._load (internal/modules/cjs/loader.js:708:14),
    at Module.require (internal/modules/cjs/loader.js:887:19),
    at require (internal/modules/cjs/helpers.js:74:18),
    at Object.<anonymous> (/usr/lib/node_modules/forever/bin/forever:3:1),
/usr/lib/node_modules/forever/lib/util/config-utils.js:22,
    throw new Error('Failed to create directory '+dir+":" +error.message);,
    ^
```

**Comment by quorn23** [comment] 2021-04-30 22:26
Duplicate of: https://github.com/Tzahi12345/YoutubeDL-Material/issues/361

**Comment by Tzahi12345** [comment] 2021-05-13 04:01
Should be fixed in the latest nightly, but if not, @quorn23 is right, go over to #361 and we can discuss further there.

**Closed by Tzahi12345** 2021-05-13 04:01 UTC
Labels: duplicate
