### ISSUE TITLE
[BUG] Download error with subscriptions.

### ISSUE THREAD

**Issue by u0a1009** [Tzahi12345/YoutubeDL-Material#473] opened 2021-09-30 06:03 UTC
Hello, I'm using nightly.
I'm currently subscribing https://youtube.com/c/%ED%9B%BC%EC%82%AC%EC%9B%90 on youtube-dl material.

<img width="1148" alt="스크린샷 2021-09-30 14 52 25" src="https://user-images.githubusercontent.com/42744904/135395243-9c1ba68e-f8d3-48e3-b2f1-40164adac9e3.png">

I only changed subscription setting like this, "Download videos uploaded in the last 2 days."
And it suddenly starts downloading same video twice, and occurs error.

<img width="1440" alt="스크린샷 2021-09-30 14 57 27" src="https://user-images.githubusercontent.com/42744904/135395609-22f22a31-e583-45c1-af62-01186fd36501.png">

First video's error : ERROR: unable to rename file: [Errno 2] No such file or directory
Second video's error : ERROR: Conversion failed!
And it creates these five files.

<img width="558" alt="스크린샷 2021-09-30 14 52 39" src="https://user-images.githubusercontent.com/42744904/135395663-ee111db8-481e-4363-be69-fcfbda79c63a.png">

When I download that video independently, it downloads well.
I think this problem happens only that channel for me.

So I think this bug occurs because of downloading same video twice at the same time, but I cannot figure out why it only happens in that channel.

Please let me know if the same problem occurs in your server or not.

**Comment by dejan995** [comment] 2021-10-02 03:15
I can confirm that this is happening with this channel. But not with the other 5-6 channels and playlists I tried. Only difference for me is that the first download was successful and I did not get a conversion error on it.

Here is a complete log with only that channel:
```
2021-10-01T20:56:43.029Z VERBOSE: Subscription: getting videos for subscription 훼사원 with args: --dump-json,-o,subscriptions/channels/훼사원/%(title)s.%(ext)s,-ciw,--write-info-json,--print-json,-f,bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4,--dateafter,now-2days,--write-thumbnail
2021-10-01T21:21:09.172Z VERBOSE: Subscription: finished check for 훼사원
2021-10-01T21:21:16.188Z VERBOSE: Collecting info for download 49888815-95ee-4b9a-a7f2-702800472d56
2021-10-01T21:21:16.246Z VERBOSE: Collecting info for download c3c73e32-c28e-4d77-bb8e-60c59ad8211f
2021-10-01T21:21:16.247Z VERBOSE: Collecting info for download 2a295cf6-779b-4dac-b709-13a843357fd1
2021-10-01T21:21:17.107Z VERBOSE: youtube-dl args being used: -o,subscriptions/channels/훼사원/%(title)s.%(ext)s,--write-info-json,--print-json,-f,bestvideo+bestaudio,--merge-output-format,mp4,--write-thumbnail
2021-10-01T21:21:17.186Z VERBOSE: youtube-dl args being used: -o,subscriptions/channels/훼사원/%(title)s.%(ext)s,--write-info-json,--print-json,-f,bestvideo+bestaudio,--merge-output-format,mp4,--write-thumbnail
2021-10-01T21:21:17.189Z VERBOSE: youtube-dl args being used: -o,subscriptions/channels/훼사원/%(title)s.%(ext)s,--write-info-json,--print-json,-f,bestvideo+bestaudio,--merge-output-format,mp4,--write-thumbnail
2021-10-01T21:22:12.625Z VERBOSE: Downloading 2a295cf6-779b-4dac-b709-13a843357fd1
2021-10-01T21:22:17.527Z VERBOSE: Downloading 49888815-95ee-4b9a-a7f2-702800472d56
2021-10-01T21:22:17.529Z VERBOSE: Downloading c3c73e32-c28e-4d77-bb8e-60c59ad8211f
2021-10-01T21:59:39.443Z ERROR: ERROR: unable to rename file: [Errno 2] No such file or directory
2021-10-01T22:00:23.318Z ERROR: ERROR: unable to rename file: [Errno 2] No such file or directory
2021-10-01T22:02:25.393Z VERBOSE: Disabling checking downloads as none are available.
```

@Tzahi12345 Any idea what might be causing this?
The arguments being passed look like they are okey, but why does it request the same video 3 times?

**Comment by GlassedSilver** [comment] 2021-10-03 11:55
I've had this before myself, not quite sure what's happening here.

**Comment by u0a** [comment] 2021-10-03 12:25
I experienced similar problems in other channels too.
Could the channel name or video title in Korean be a problem?
It is strange that problems do not occur in general downloads(not with subscriptions).

**Comment by GlassedSilver** [comment] 2021-10-03 13:42
> 
> I experienced similar problems in other channels too. Could the channel name or video title in Korean be a problem? It is strange that problems do not occur in general downloads(not with subscriptions).

It might be that the videos I have had this issue with before have been JP/KO videos as well.

As for the double download, are you using the archive feature?

**Settings > Downloader > Use youtube-dl archive** set to **yes**

![image](https://user-images.githubusercontent.com/1912133/135756169-bec81f71-9db3-40aa-9150-9134502f0cec.png)

**Comment by u0a** [comment] 2021-10-03 13:48
> It might be that the videos I have had this issue with before have been JP/KO videos as well.
> 
> 
> 
> As for the double download, are you using the archive feature?
> 
> 
> 
> **Settings > Downloader > Use youtube-dl archive** set to **yes**
> 
> 
No I didn't use archive feature because double download occur at the same time.
Will it be good to turn on that option?

**Comment by GlassedSilver** [comment] 2021-10-03 13:51
I find the archive feature to be a requirement in my honest opinion. IMHO it should be defaulted to true.

Try using the archive feature, might help you out quite a bit.

That particular behavior has been spotted before, and I think it got remedied through this function.

**Comment by u0a** [comment] 2021-10-04 00:55
> I find the archive feature to be a requirement in my honest opinion. IMHO it should be defaulted to true.
> 
> 
> 
> Try using the archive feature, might help you out quite a bit.
> 
> 
> 
> That particular behavior has been spotted before, and I think it got remedied through this function.

Thanks but it didn't work.
Maybe there's another problem  that we don't know.

**Comment by u0a** [comment] 2021-10-04 01:01
However, luckily, one fails but one succeeds from some point. Although two download records will be taken, this doesn't look bad.

**Comment by GlassedSilver** [comment] 2022-04-17 12:13
I'll close this issue now, because I assume this is resolved.

The download records are basically just providing a job list. It can be safely cleared. Manual jobs may still linger in there that don't get automatically re-submitted as new job, so use the `Clear finished downloads` button with care.

**Closed by GlassedSilver** 2022-04-17 12:13 UTC
Labels: bug
