### ISSUE TITLE
Errors in logs using the Docker `nightly` branch

### ISSUE THREAD

**Issue by tehniemer** [Tzahi12345/YoutubeDL-Material#345] opened 2021-03-07 15:05 UTC
I'm seeing some consistent errors in my logs and I'm not sure what it's really telling me. It doesn't seem like the permission error is of a location I have control over.

```
OSError: [Errno 13] Permission denied: '/.cache',
WARNING: Writing cache to u'/.cache/youtube-dl/youtube-sigfuncs/js_a09205f7_104.json' failed: Traceback (most recent call last):,
  File "/app/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/cache.py", line 49, in store,
    os.makedirs(os.path.dirname(fn)),
  File "/usr/lib/python2.7/os.py", line 150, in makedirs,
    makedirs(head, mode),
  File "/usr/lib/python2.7/os.py", line 157, in makedirs,
    mkdir(name, mode)
```

My compose file is below
```
## YoutubeDL-Material - Material Design frontend for youtube-dl
  ytdl:
    image: tzahi12345/youtubedl-material:nightly
    container_name: ytdl
    restart: unless-stopped
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
#    ports:
#      - '$YTDL_PORT:17442'
    volumes:
      - '$DOCKER_DIR/ytdl:/app/appdata'
      - '$MEDIA_DIR/YouTube/Audio:/app/audio'
      - '$MEDIA_DIR/YouTube/Video:/app/video'
      - '$MEDIA_DIR/YouTube/Users:/app/users'
      - '$MEDIA_DIR/YouTube/Subscriptions:/app/subscriptions'
    environment:
      ALLOW_CONFIG_MUTATIONS: 'true'
      UID: $PUID
      GID: $PGID
    labels:
      - 'traefik.enable=true'
      ## HTTP Routers
      - 'traefik.http.routers.ytdl-rtr.entrypoints=https'
      - 'traefik.http.routers.ytdl-rtr.rule=Host(`ytdl.$DOMAINNAME`)'
      ## Middlewares
      - 'traefik.http.routers.ytdl-rtr.middlewares=chain-authelia@file' #Authelia Authentication
      ## HTTP Services
      - 'traefik.http.routers.ytdl-rtr.service=ytdl-svc'
      - 'traefik.http.services.ytdl-svc.loadbalancer.server.port=17442'
```

**Comment by Tzahi12345** [comment] 2021-03-07 19:38
Where is $MEDIA_DIR pointed to? I assume it's an NFS share.

This is actually a duplicate of [this issue](https://github.com/Tzahi12345/YoutubeDL-Material/issues/186), so if you don't mind I'll go ahead and close this issue so we can have one place to hone in on this problem (there may be an easy workaround here like setting the UID/GID to the correct values.

**Closed by Tzahi12345** 2021-03-07 19:38 UTC
Labels: duplicate

**Comment by tehniemer** [comment] 2021-03-07 20:31
It's a SAMBA share, but yes, it is a share. I'll add comment to the other issue.
