### ISSUE TITLE
[BUG] - Audio does not download with video

### ISSUE THREAD

**Issue by modem7** [Tzahi12345/YoutubeDL-Material#438] opened 2021-09-06 14:23 UTC
**Describe the bug**
Videos do not download with audio, only video.

**To Reproduce**
Video: https://www.youtube.com/watch?v=VWDpWmc5Yys
![image](https://user-images.githubusercontent.com/4349962/132230554-8fcc0ea3-95d5-41be-99a8-0b20cacac08a.png)

**Expected behavior**
Video downloaded w/ audio

**Screenshots**

**Environment**
```yaml
  ytdl_material:
    container_name: YTDL_Material
    image: tzahi12345/youtubedl-material:nightly
    volumes:
      - $DOWNLOADDIR/downloads/Youtube-dl-mat/appdata:/app/appdata
      - $DOWNLOADDIR/downloads/Youtube-dl-mat/audio:/app/audio
      - $DOWNLOADDIR/downloads/Youtube-dl-mat/video:/app/video
      - $DOWNLOADDIR/downloads/Youtube-dl-mat/subscriptions:/app/subscriptions
      - $DOWNLOADDIR/downloads/Youtube-dl-mat/users:/app/users
    environment: 
      ALLOW_CONFIG_MUTATIONS: 'true'
      ytdl_use_local_db: 'true'
      write_ytdl_config: 'true'
      UID: $PUID
      GID: $PGID
    networks:
      - isonet
    ports:
      - "8998:17442"
    restart: always
```

JSON attached
[video.info.json.zip](https://github.com/Tzahi12345/YoutubeDL-Material/files/7116547/video.info.json.zip)

**Comment by Tzahi12345** [comment] 2021-09-06 22:25
What's likely happening is the audio codec you're using isn't supported -- the .info.json suggests it's mp4a which I feel should be universal... Can you try opening up the file in VLC and seeing if it works? Also, what OS are you using?

**Comment by modem7** [comment] 2021-09-06 22:28
Heya, 

In this particular case, I'm just doing default settings, no custom settings on the GUI. 

I've attempted VLC, but unfortunanately still no audio. 

I'm using Ubuntu LTS for Docker, and Windows 10 for viewing on VLC (I've set it to download to a Samba share)

**Comment by GlassedSilver** [comment] 2021-09-11 23:37
I've had an occurance of that issue before as well myself, not sure which one of my many it was though, so I'm afraid I can't contribute telemetry and samples myself.

I think (?) for me a redownload solved it? Although obviously an unmonitored system should catch this, I agree. Sorry to be of little help here other to verify that this happened over here as well at some point. (unRAID, nightly latest, etc... you know my system well enough by now, @Tzahi12345  :P )

**Comment by dejan995** [comment] 2021-09-25 20:34
Hello all.
Just to add to this. I had this same bug happen to me.

@GlassedSilver I tried the redownload option a couple of times but it didn't work. I even tried it with different video quality options, still no sound, just video.

On the other hand it did manage to download in Audio Only mode and it's playing properly but with no video.

I have the exact same configuration as @modem7.

This is the video I tried downloading: [[4K] Dreamcatcher - BEcause | stage NEON](https://www.youtube.com/watch?v=ykkRcmAZAzo)

In the attachments you can find the JSON files for both the Video and the Audio downloads I did. Maybe they will shed some light on what is going on. [JSON.zip](https://github.com/Tzahi12345/YoutubeDL-Material/files/7230301/JSON.zip)

Docker did not generate any usefull logs.

@Tzahi12345 I tried playing the video using my Jellyfin Media Server (no audio track, just video), VLC on Win10 (no audio track, just video), the default Video Player in Win10, Android version of Jellyfin Media Sever and Android Version of VLC.

What I mean by "no audio track, just video" is that those applications detect the file as only having a "Video Track" on it. I've included a pictures as well. 

This leads me to belive that this has to be something with youtube-dl and the codec it uses to encode the files. But I'm not 100% sure beacuse I have never used youtube-dl on its own, I have always used frontends for it.

![audiocodec](https://user-images.githubusercontent.com/40325303/134785263-c4957136-5eea-4096-9f01-a0103a1cfcb0.png)

**Comment by Tzahi12345** [comment] 2021-09-26 00:16
@dejan995 can you turn on verbose logging and show the args that get used with the video? You'll have to restart, but it will show exactly what's being used and may help debug why it's not working. I'll take a look later tonight and see if I can reproduce!

**Comment by dejan995** [comment] 2021-09-26 16:10
@Tzahi12345 Here is what I got.

**Using the single download option on the homepage. This downloads only the video, without audio.**
`2021-09-26T15:11:26.947Z VERBOSE: youtube-dl args being used: -o,video/%(title)s.mp4,--write-info-json,--print-json,-f,400,--write-thumbnail`

**Using the playlist subscription option. This downloads video and audio.**
`2021-09-26T15:17:27.044Z VERBOSE: youtube-dl args being used: -o,subscriptions/playlists/stage NEON | 스테이지 네온/%(title)s.%(ext)s,--write-info-json,--print-json,-f,bestvideo+bestaudio,--merge-output-format,mp4,--write-thumbnail`

I executed inside the Docker container and used the first set of options with the youtube-dl binary provided in the docker image, same result, only video, no audio.

I think the key here are the **bestvideo+bestaudio** and **merge-output-format** options. Just a thought, not 100% sure.

**Comment by u0a** [comment] 2021-09-27 06:58
I was having same issue with him, with https://www.youtube.com/watch?v=UpdhoAhX_YM 
When I downloaded, I couldn't hear the audio, and when I turned on audio only mode, I could hear audio normally.

So I changed downloader to youtube-dlc, and all worked!
Go to Settings - Advanced - Select downloader and select youtube-dlc.

**Comment by dejan995** [comment] 2021-09-27 13:56
@u0a I tried with youtube-dlc and it didn't work.
But this made me realize that this only happens when I select a diferent quality for the video. When I leave it at default (MAX) it downloads the video+audio. Using both youtube-dl & youtube-dlc.

@Tzahi12345 The arguments passed when downloading with the default MAX option are: 

`2021-09-27T13:16:20.750Z VERBOSE: youtube-dl args being used: -o,video/%(title)s.mp4,--write-info-json,--print-json,-f,bestvideo+bestaudio,--merge-output-format,mp4,--write-thumbnail`

Same as when downloading the video as a playlist, as I explained previosly.
I looked over some of the code but couldn't find from where the application takes the arguments when a different quality is selected.

I have no idea how this application works but a possible fix is to have the youtube-dl arguments being passed be like this:
`o,video/%(title)s.mp4,--write-info-json,--print-json,-f,best[height=1440]+bestaudio,--merge-output-format,mp4,--write-thumbnail`
Where the "1440" will be a variable that will depend on the user input from the dropdown list on the homepage.
This will break the "MAX" option because it uses a different syntax. Solution for this one is to have an IF statment that will detirmen which syntax to use. If the user selects "MAX" it will use **bestvideo+bestaudio** and if the user selects a different option it will use **best[height=_var_]+bestaudio**.

@Tzahi12345 I don't understand JS that much, so I am not able to implement this on my own. But if you come up with something I'm more than willing to test it out and provide feedback.

**Comment by Tzahi12345** [comment] 2021-09-29 02:32
@modem7 @dejan995 Thanks for the help with debugging this!

Long story short, if you selected a video quality that didn't have the audio built in, it wouldn't add one automatically (despite the logic being there) due to a bug. [See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/84fa425a993577ccbe6c3b05c8187500d87a7ef8).

We're doing something similar to MeTube with a couple differences:
* If you select a quality level, do some additional preprocessing to determine the format_id (ex. `400` or `22`) and adding an audio format if one doesn't exist (looks something like `400+172`)
* If it's left on max, we just do `bestvideo+bestaudio`
* For both of these approaches we add `--merge-output-format mp4`

Anyways it should be fixed now!

**Closed by Tzahi12345** 2021-09-29 02:32 UTC
Labels: bug

**Comment by dejan995** [comment] 2021-09-29 22:06
Just to confirm that this is now working.
Although I opened and linked a new issue about an error message that has started to appear after this fix.
