### ISSUE TITLE
Subscriptions on Synology

### ISSUE THREAD

**Issue by geekedtv** [Tzahi12345/YoutubeDL-Material#101] opened 2020-05-24 13:07 UTC
So after running the app in docker on Synology for a week, here are my issues and they are all with Subscriptions.

For each subscription check, it runs the execution command at 7-9% CPU. This can really add up if you have a lot of subscriptions and it runs a few at a time. https://i.imgur.com/XYiECWf.jpg

I noticed in the command it runs the "dateafter now-xdays" replacing "x" with amount of days you chose. So this tells me it's checking those days every single time it runs the command causing the command to stay in the queue until it checks every day causing the CPU to throttle until it's done checking. Why not let us just subscribe and only get new videos from the time the subscription was added? We shouldn't have to choose a day to add a subscription. Just add a subscription and it will run a check for new videos after that.

I changed the check interval to 1200 and this seems to help a lot. Especially if you have over 5 subscriptions. It is not a means to an end though because the checks are taking way too long when it runs the "dateafter now-xdays" along with it. It should only do that once then only check for new videos after that.

A bug I found

If you unsubscribe and add the same subscription back, it will NOT download videos from that subscription. Even after restarting the container.

Subscriptions is really the only thing I want to use right now and it needs a lot of work. I am running this along side Emby for my 5 year old son so he can watch videos without being online. It's a great way for me to control what he's watching. And before you ask, no, my son is not watching JRE lol. Those were just channels I was testing with in the screenshot above.

**Comment by geekaroni** [comment] 2020-05-24 14:00
Pretty sure I found the culprit here. If I add subscriptions by checking "download all uploads" it seems to run fine so far. I think adding subscriptions based on videos upload in the last X days results in heavy cpu usage because it runs that script every check.

Something to look into.

**Comment by Tzahi12345** [comment] 2020-05-24 18:12
Did some more research, it looks like you are right. Here's a [relevant issue](https://github.com/ytdl-org/youtube-dl/issues/1502) on the youtube-dl GitHub. Apparently someone submitted a [PR that addresses this](https://github.com/ytdl-org/youtube-dl/pull/17893), but it hasn't been merged and it looks largely ignored by the authors.

We might need to start thinking about workarounds beyond just not using that option. One idea is to do a pre-check, where we find all the videos that do *not* fit into the `--dateafter`. We only need to do this once, and store all of the IDs into an archive file using the `--download-archive`. Basically, this arg will tell youtube-dl to avoid certain videos, acting as a blacklist.

If the blacklisting of videos in the archive is a fast operation, it might significantly cut down the time it takes to do the check even with the --dateafter arg. It's just an idea, but I think we're gonna have to get creative unless youtube-dl comes through by merging that PR.

**Comment by Tzahi12345** [comment] 2020-05-25 19:42
Here's the stopgap I'm planning on using: if a subscription is still being checked, it will be skipped until the next check (defined by the interval). This doesn't apply to all subscriptions, just the ones that aren't finished yet.

The end result for this is some subscriptions will take longer to run, but the underlying problem of subscription checks for the same subscription piling on after each check will be resolved (no more high CPU/RAM usage). I've tested and pushed this to the nightly tag, let me know if the problem is resolved on your end! [Here's the commit.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/c8a80460560c4d4fdaa7554fb22002dea64067d9)

I'm normally much better at getting hotfixes out, but I just started an internship a couple weeks ago that has been taking much of my time, so things are going a bit more slowly than I'd like.

I'll keep this issue open until I address the other bug you brought up regarding adding/deleting subscriptions. Thanks again for all the info, it was super helpful in helping get a solution out. I'll also think about ways to minimize the time it takes for checks for individual subscriptions, maybe the solution I described above will help.

**Comment by geekaroni** [comment] 2020-05-25 22:27
Not a problem! Your work is more important! However, your response to this project has also been great. I’m happy with how you’re handling the issues that came flooding in after I started promoting it lol. Glad to test and report back.

On another note, I did test adding 5 subscriptions with download all videos option and haven’t had any issues with CPU for long periods of time. Only for a few seconds while it runs checks and ffmpeg does it’s thing.

Looking forward to testing your new commit!

**Comment by geekaroni** [comment] 2020-05-29 15:37
Just an update. The cpu issue seemed to be fine right now. However, the RAM is going crazy now when downloading videos.

![image](https://user-images.githubusercontent.com/57927413/83277930-c6c72280-a1a0-11ea-91db-5b575f38c5c0.png)

**Comment by Tzahi12345** [comment] 2020-05-30 20:45
Agh the bug just doesn't wanna get fixed! :P

Can you check the list of processes again and see what might be causing the issue (basically, which process is eating all that RAM??)

Maybe the CPU and RAM issue were unrelated, and there may be a memory leak. Hard to know without additional info.

**Comment by powerdude** [comment] 2020-06-26 19:56
> 
> 
> Just an update. The cpu issue seems to be fine right now. However, the RAM is going crazy now when downloading videos.
> 
> ![image](https://user-images.githubusercontent.com/57927413/83277930-c6c72280-a1a0-11ea-91db-5b575f38c5c0.png)

@nashosted what app are you using to monitor that allows you to monitor the docker image?

**Comment by GlassedSilver** [comment] 2022-04-28 07:22
Still an issue on the latest nightly?

**Closed** 2022-05-22 03:40 UTC
Labels: is: bug, 💬 response-needed, SUBSCRIPTIONS
