### ISSUE TITLE
[BUG] No default admin account detected (when one has been made previously)

### ISSUE THREAD

**Issue by tyzbit** [Tzahi12345/YoutubeDL-Material#492] opened 2021-11-10 14:14 UTC
**Describe the bug**
After setting up the application, subscribing to playlists, downloading videos eventually I am presented with "No default admin account detected" even though I had previously created an admin account.

**To Reproduce**
_Unknown_

**Expected behavior**
Accounts and data that is created or saved should not become corrupt.

**Screenshots**

**Environment**
- YoutubeDL-Material version
`v4.2`
- Docker tag: `tzahi12345/youtubedl-material@sha256:9a5304ed3a3a5a205c88f84bbf40668bd247c77d53102146085979e22725cb21` (`latest` built on `2021/09/26`)

**Additional context**
```
/app/appdata # ls -al
total 4368
drwxr-xr-x    1 youtube  youtube        386 Nov 10 05:10 .
drwxr-xr-x    1 youtube  youtube       4096 Nov 10 05:10 ..
drwxr-xr-x    1 youtube  youtube          0 Mar 23  2021 archives
-rw-r--r--    1 youtube  youtube        982 Nov 10 05:10 db.json
-rw-r--r--    1 youtube  youtube        938 Sep 18 15:20 db.json.1631978448.319.bak
-rw-r--r--    1 youtube  youtube        193 Oct 10 02:55 db.json.1633834537.714.bak
-rw-r--r--    1 youtube  youtube        125 Mar 23  2021 db.old.json
-rw-r--r--    1 youtube  youtube       2174 Sep 23 02:37 default.json
-rw-r--r--    1 youtube  youtube        166 Nov 10 05:10 local_db.json
drwxr-xr-x    1 youtube  youtube         42 Oct 10 03:17 logs
-rw-r--r--    1 youtube  youtube    2213150 Nov 10 05:10 users.json
-rw-r--r--    1 youtube  youtube        257 Mar 23  2021 users.old.json
-rw-r--r--    1 youtube  youtube    2213150 Sep 18 15:20 users_db.json.1631978448.32.bak
-rw-r--r--    1 youtube  youtube        405 Oct 10 02:55 users_db.json.1633834537.72.bak
```

**Comment by GlassedSilver** [comment] 2021-12-16 12:04
Latest built on Sept 26, 2021?

Are you sure you're not on the nightly tag?

**Comment by tyzbit** [comment] 2021-12-16 15:00
It's possible I am.

**Comment by GlassedSilver** [comment] 2021-12-16 16:58
I don't run in multi-user mode, so I fear I can't reproduce this with my setup.

I know it's been a while since you opened this ticket, but do you have the logs of when this started by any chance still?

Those users jsons (the active one and the backup) could also possibly be of help.

Maybe @Tzahi12345 can help out here. Not sure. He seems pretty preoccupied at the moment, so it could be we'll need a bit of time to tackle this. Sorry that I don't have much more uplifting guidance at the moment.

However, as I said, any telemetry could be helpful here.

**Comment by tyzbit** [comment] 2021-12-16 18:26
Unfortunately I only retain 1 month of logs and I haven't touched ytdl since this happened for fear of wiping out the videos I've already downloaded from the database.

**Comment by Tzahi12345** [comment] 2022-04-24 01:29
If you back up your appdata folder you should be able to pull it without fear (as long as your video, audio, and users folders are properly mounted)

Were you using MongoDB or just the default?

**Comment by tyzbit** [comment] 2022-04-24 02:25
I was using the default.

**Comment by Tzahi12345** [comment] 2022-04-24 03:14
Could you by chance share you local_db.json file? It does contain all the videos you downloaded, just letting you know. If you're not comfortable sharing that publicly you can also email me it isaacmoabadi@gmail.com

**Comment by tyzbit** [comment] 2022-04-24 03:30
I've since started again from scratch without using the built in authentication and haven't run into any issues. In addition, virtually all of my videos were downloaded via subscriptions. In any case, here's my `db.json`:

<details><summary>Click to expand...</summary>
<pre>
{
  "playlists": [],
  "files": [
    {
      "id": "Flight of the Navigator _ VFXcool",
      "title": "Flight of the Navigator | VFXcool",
      "thumbnailURL": "https://i.ytimg.com/vi/tyixMpuGEL8/maxresdefault.jpg?v=6134f8de",
      "isAudio": false,
      "duration": 2488,
      "url": "https://www.youtube.com/watch?v=tyixMpuGEL8",
      "uploader": "Captain Disillusion",
      "size": 577852105,
      "path": "video/Flight of the Navigator _ VFXcool.mp4",
      "upload_date": "2021-05-20",
      "description": "Captain Disillusion leaves Alan in charge of an episode and things get rapidly nostalgic.\n\nPlease consider supporting my work on: http://www.patreon.com/CaptainDisillusion\n\nCHAPTERS:\n\n00:00 - Prologue\n01:10 - Subjectively Amazing\n08:15 - Big Slow Computers\n14:13 - Motion, but Controlled\n19:51 - Get in the Camera!\n27:00 - Arts & Crafts\n35:27 - The World Has Changed\n\nCREDITS:\n\nWritten & Directed by\nAlan Melikdjanian\r\r\n\nResearch & Additional Writing\nSamantha Kuk\n\nCamera\nEmily Wood\nVilen Melikdjanian\n\nVisual Effects & Animation\nAlan Melikdjanian\nJoey Deutsch\n\nProp Support\nBill & Brittany Doran\n3D Printing Nerd\n\nTransportation\nMichael Wood\n\nIntro Theme by\nHachik0\n\n‘Robot Romp’ Music Cover by\nJoey Deutsch\n\nStories & Images Provided by\nDave Sieg\nJeff Kleiser\nDoug MacMillan\nGeorge Muhs\nPeter Cook\nTony Urbano\nTim Blaney\nDavid Goldberg\n\rSpecial Thanks to\nAndrew James Spooner\nGlenn Campbell\nAmi Yamato\nIan Hubert\nDisney Dan\nTony Hipwell\n&\nAll of Captain Disillusion’s Patreon Supporters!",
      "view_count": 1816193,
      "height": 1080,
      "abr": 133.601,
      "thumbnailPath": "video/Flight of the Navigator _ VFXcool.jpg",
      "uid": "b8f8e5fa-b291-4113-8776-f622ef55fe19",
      "registered": 1640284704681,
      "local_view_count": 1
    }
  ],
  "configWriteFlag": false,
  "downloads": {
    "15ed04b3e6e0a305111a646695a1ab07": {
      "73574be6-6a6f-4aa6-9994-173a5aad0a95": {
        "uid": "73574be6-6a6f-4aa6-9994-173a5aad0a95",
        "ui_uid": "b4b2f02f-2027-4577-b121-3df56aaea86d",
        "downloading": false,
        "complete": false,
        "url": "https://www.youtube.com/watch?v=tyixMpuGEL8",
        "type": "video",
        "percent_complete": "182.23",
        "is_playlist": false,
        "timestamp_start": 1640273862979,
        "filesize": 577801706,
        "_filename": "video/Flight of the Navigator _ VFXcool.mp4",
        "timestamp_end": 1640283917639,
        "error": "ERROR: unable to rename file: [Errno 2] No such file or directory"
      },
      "9fe28528-3cd4-432f-b098-f51596962113": {
        "uid": "9fe28528-3cd4-432f-b098-f51596962113",
        "ui_uid": "684b5844-9b5e-4727-8a24-ed0480699311",
        "downloading": false,
        "complete": false,
        "url": "https://www.youtube.com/watch?v=tyixMpuGEL8",
        "type": "video",
        "percent_complete": "182.23",
        "is_playlist": false,
        "timestamp_start": 1640273990850,
        "filesize": 577801706,
        "_filename": "video/Flight of the Navigator _ VFXcool.mp4",
        "timestamp_end": 1640283917976,
        "error": "ERROR: unable to rename file: [Errno 2] No such file or directory"
      },
      "83816ac8-ff0d-47d8-9c6f-b291621cc1f8": {
        "uid": "83816ac8-ff0d-47d8-9c6f-b291621cc1f8",
        "ui_uid": "b5c1346f-5d07-41b2-a531-51b52a773dde",
        "downloading": false,
        "complete": true,
        "url": "https://www.youtube.com/watch?v=tyixMpuGEL8",
        "type": "video",
        "percent_complete": "100.07",
        "is_playlist": false,
        "timestamp_start": 1640274235295,
        "filesize": 577801706,
        "_filename": "video/Flight of the Navigator _ VFXcool.mp4",
        "timestamp_end": 1640284704628,
        "fileNames": [
          "video/Flight of the Navigator _ VFXcool.mp4"
        ]
      }
    }
  },
  "subscriptions": [
    {
      "name": "youtubehaiku",
      "url": "https://www.youtube.com/playlist?list=PLWh_Fb1QWWg24ofE1yYA-CNHHpyTER9P9",
      "maxQuality": "best",
      "id": "4cd645b3-7b39-4e2a-8814-6cf4eabf091f",
      "streamingOnly": false,
      "user_uid": null,
      "type": "video",
      "isPlaylist": true,
      "downloading": false
    },
    {
      "name": "music box tunes",
      "url": "https://www.youtube.com/playlist?list=PLWh_Fb1QWWg2URlJiYFOAnkczWz7sT_Me",
      "maxQuality": "best",
      "id": "f577ae01-d2c3-40eb-9a77-ab3008f8aa41",
      "streamingOnly": false,
      "user_uid": null,
      "type": "video",
      "isPlaylist": true,
      "downloading": false
    },
    {
      "name": "Chill Video Game Music",
      "url": "https://www.youtube.com/playlist?list=PLWh_Fb1QWWg1XI23xsTNFcRwRFb4NP2M4",
      "maxQuality": "best",
      "id": "ad2ef033-3e69-4104-995e-9a80c9dbafc6",
      "streamingOnly": false,
      "user_uid": null,
      "type": "video",
      "isPlaylist": true,
      "archive": "/app/subscriptions/archives/Chill Video Game Music",
      "downloading": false
    }
  ],
  "files_to_db_migration_complete": false,
  "simplified_db_migration_complete": true,
  "categories": [],
  "new_db_system_migration_complete": true
}
</pre>
</details>

**Comment by Tzahi12345** [comment] 2022-05-02 04:47
Hi @tyzbit, I believe I fixed the issue with [this commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/d5c1361e64a207973ff82e92811c884d1fa3ed7c)! I think it's a duplicate of #561. If you run into any issues let me know.

**Closed by Tzahi12345** 2022-05-02 04:47 UTC
Labels: is: bug
