### ISSUE TITLE
Arguments are not working

### ISSUE THREAD

**Issue by mokshmridul** [Tzahi12345/YoutubeDL-Material#85] opened 2020-05-18 05:02 UTC
I would like to start by thanking you for making this application. It makes life a lot simpler.

I am trying to use the following commands, but it is failing to download any clips:

`#"--merge-output-format mkv,,-f bestvideo[height<=?1440]+bestaudio/best,,--prefer-ffmpeg,,--add-metadata,,--write-srt --sub-lang en --sub-format best,,--convert-subs srt,,--output \"video/%(uploader)s - %(title)s.%(ext)s\""`

I think its the `-f` flag that is causing an error, but some of the others are also not working.

**Comment by Tzahi12345** [comment] 2020-05-18 13:46
Glad you like the app!

Quick question: are these custom args from Advanced download mode or from the global custom args in the settings?

Also, one thing I noticed is some of the args aren't delimited by the double commas (`--write-srt`, `--sub-lang`, etc.) I would also recommend splitting the arg and their value to avoid additional errors (ex. `--convert-subs srt` -> `--convert-subs,,srt`).

Lastly (and this is probably what's ultimately making it fail), this app currently only supports mp3 and mp4 files. I've been wanting to make it "file extension agnostic" for a bit now, but I haven't gotten to it yet.

Hope this helps, let me know if it still fails after making the adjustment.

**Comment by mokshmridul** [comment] 2020-05-19 15:52
Thank you so much for the quick revert on this.

I took some of your suggestions and made the following changes

`"--merge-output-format,,mkv,,-f,,bestvideo[height<=?1440]+bestaudio/best,,--prefer-ffmpeg,,--add-metadata,,--write-srt,,--sub-lang,,en,,--sub-format,,best,,--convert-subs,,srt"`

Using this doesn't work, but now i dont even get an error message like previously. The download progress bar simply keeps looping.

**Comment by Tzahi12345** [comment] 2020-05-19 17:11
I would still recommend changing the `--merge-output-format`, as this app doesn't currently know how to handle video files that *aren't* mp4s. So instead of merging into mkv, you should merge into mp4. Hope this makes sense.

Let me know if this helps! Also, if you can share the video you're trying on so I can try to reproduce the bug, that would be super helpful.

**Comment by mokshmridul** [comment] 2020-05-19 17:18
Okay, i see your point. I am now trying with this config

`"--prefer-ffmpeg,,--add-metadata,,--write-srt,,--sub-lang,,en,,--sub-format,,best,,--convert-subs,,srt"`

with this YT video: https://www.youtube.com/watch?v=zHky9TCfT68

It still is not downloading subs. I also want to use the following args, but cant seem to get them to work:

1) `-f bestvideo[height<=?1440]+bestaudio/best`
2) `--output "vidoe/%(uploader)s - %(title)s.%(ext)s"`, where "video" is the download directory

**Comment by Tzahi12345** [comment] 2020-05-19 23:18
Ah, I feel like an idiot for not noticing this earlier. There are two required custom args (I should just make it so they're always included):

`--print-json` and `--write-info-json`. They're both essential to getting information on a video after it downloads. Because they were missing, it failed. This should work for the video you provided:

`--merge-output-format,,mp4,,--add-metadata,,--write-srt,,--sub-lang,,en,,--sub-format,,best,,--convert-subs,,srt,,--output,,video/%(uploader)s - %(title)s.%(ext)s,,--write-info-json,,--print-json,,-f,,bestvideo[height<=?1440]+bestaudio/best`

**Comment by mokshmridul** [comment] 2020-05-20 03:41
Hi,

the configuration provided above still doesnt download the video. The progress bar keeps looping, as shown in the picture below

![Capture](https://user-images.githubusercontent.com/8089422/82402399-e6ac6700-9a79-11ea-96b0-87f258b4c4fc.PNG)

**Comment by Tzahi12345** [comment] 2020-05-20 14:24
Strange, as it works on my end.

Do you get a different error for that configuration?

**Comment by mokshmridul** [comment] 2020-05-20 15:46
Unfortunately i get no error message on screen, and nor do i get anything in the logs

**Comment by Tzahi12345** [comment] 2020-05-20 16:22
Hm, ok. And are you putting the custom args in the settings, or using the "Advanced download mode"? Just wanna make sure you're putting the args in the right place.

**Comment by mokshmridul** [comment] 2020-05-20 17:20
im putting them through the "Advanced Download Mode" page. But let me try removing it and starting from scratch.

**Comment by Tzahi12345** [comment] 2020-05-20 21:55
Damn sorry you can't get it working :(

I'm not sure if you've tried removing each arg individually until it's fixed to try to determine the one that's causing the issues. If not, it might be worth a try. Otherwise, not sure what else could get us closer to finding out what's wrong. It's pretty weird that it doesn't display any errors.

**Comment by magnusv0s** [comment] 2020-05-30 03:19
Hi, so I have had some difficulty trying to get the custom arguments to work and I think I have potentially found the problem.

When I enter them using the advanced settings section, they work fine, the argument that is says it is going to run in the Simulated command section looks good, o problems, but then when I make the same changes in the Downloader custom args section, the Simulated command has both the custom args that I entered as well as the default ones rather than the default being replaced.

**Comment by GlassedSilver** [comment] 2022-04-28 06:31
I'm pretty sure this is resolved by now (at least on the nightlies, can't remember when I last used release-channel :P).
If not, please correct me, and I'll reopen!

**Closed by GlassedSilver** 2022-04-28 06:31 UTC
