### ISSUE TITLE
[Bug] Allow advanced download option doesn't close settings pane

### ISSUE THREAD

**Issue by UnlimitedCookies** [Tzahi12345/YoutubeDL-Material#144] opened 2020-06-28 23:26 UTC
Selecting `Allow advanced download` in the Settings under `Advanced` somehow disables the functionality to save the settings.
The button turns blue, but is not clickable.

It does change the setting if you press the save button and manually reload the site with `f5`. Pressing cancel rejects the changes.

Best regards.

**Comment by Tzahi12345** [comment] 2020-06-29 06:37
Hm, I'm not able to reproduce. Do you see anything in your browser console logs? Or maybe docker container logs?

![](https://i.imgur.com/jxGrpqA.gif)

**Comment by UnlimitedCookies** [comment] 2020-06-29 16:35
There's actually an error in the console log:

![Github YTDL Bug lol](https://user-images.githubusercontent.com/49200216/86032060-0b134000-ba37-11ea-8065-0e1a619f4046.gif)
[ytdl.klvdorner.de-1593448472545.log](https://github.com/Tzahi12345/YoutubeDL-Material/files/4846801/ytdl.klvdorner.de-1593448472545.log)

**Comment by Tzahi12345** [comment] 2020-06-30 04:25
Sounds like a server-side issue (something had to have gone wrong in the saving of the config file). Do you see any container-side logs?

Also, if you can go into the Network tab in the Chrome DevTools, you should see the setConfig API calls going out. If you can paste the request payload over in the bottom of the Headers tab, that might point to what's going on (maybe that JSON is malformed)

Alternatively, you can make an admin account and email me the credentials at IsaacMGrynsztein@gmail.com, so I can try it out on your instance myself and see if I can find anything weird.

**Comment by UnlimitedCookies** [comment] 2020-07-01 18:06
> Alternatively, you can make an admin account and email me the credentials at IsaacMGrynsztein@gmail.com, so I can try it out on your instance myself and see if I can find anything weird.

I've emailed you the credentials (but haven't got a response yet). So I just want to remind you to check the Junk folder :D

**Comment by Tzahi12345** [comment] 2020-07-01 19:34
Sorry, must have missed it! Will do some investigating today, thanks for the reminder :)

**Comment by Tzahi12345** [comment] 2020-07-01 22:00
Ok, so I tried changing `Allow advanced download` and ran into the same problem. In fact, when I tried to save any setting I got the same error.

Do you really see no errors in the container logs? Something must be erroring after saving the new config, I'm starting to think it's a backend issue now. Let me know if you see anything interesting!

**Comment by UnlimitedCookies** [comment] 2020-07-01 22:05
These are the container logs:
```
2020-07-01T19:33:40.392Z ERROR: User isaac not found
2020-07-01T19:33:45.658Z ERROR: User issac not found
2020-07-01T19:33:49.431Z ERROR: User Issac not found
2020-07-01T19:39:17.773Z ERROR: User tzahi not found
2020-07-01T19:39:22.437Z ERROR: User tzahi12345 not found
TypeError [ERR_INVALID_URL]: Invalid URL:
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at loadConfigValues (/app/app.js:605:18)
    at /app/app.js:1838:9
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at compression (/app/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
TypeError [ERR_INVALID_URL]: Invalid URL:
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at loadConfigValues (/app/app.js:605:18)
    at /app/app.js:1838:9
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at compression (/app/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
TypeError [ERR_INVALID_URL]: Invalid URL:
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at loadConfigValues (/app/app.js:605:18)
    at /app/app.js:1838:9
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at compression (/app/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
TypeError [ERR_INVALID_URL]: Invalid URL:
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at loadConfigValues (/app/app.js:605:18)
    at /app/app.js:1838:9
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at compression (/app/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
TypeError [ERR_INVALID_URL]: Invalid URL:
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at loadConfigValues (/app/app.js:605:18)
    at /app/app.js:1838:9
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at compression (/app/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
TypeError [ERR_INVALID_URL]: Invalid URL:
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at loadConfigValues (/app/app.js:605:18)
    at /app/app.js:1838:9
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at compression (/app/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
TypeError [ERR_INVALID_URL]: Invalid URL:
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at loadConfigValues (/app/app.js:605:18)
    at /app/app.js:1838:9
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at compression (/app/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
TypeError [ERR_INVALID_URL]: Invalid URL:
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at loadConfigValues (/app/app.js:605:18)
    at /app/app.js:1838:9
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at compression (/app/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
```

**Comment by Tzahi12345** [comment] 2020-07-01 22:26
Awesome logs! I think I know what's causing the issue. The `url` setting in the config is empty, so when app.js:loadConfigValues() tries to parse it into a URL object, it crashes. On container startup this error should actually appear as well. If it doesn't, then something strange is going on here.

You can fix this by manually changing your `default.json` and setting your `url` to your actual URL, follow this format: `http://example.com`.

The URL setting isn't actually useful for Docker users, but in certain instances (like for non-Docker users) it can come in handy. As a result, any URL you put in there would work (including `http://example.com`) no problem.

To fix this long-term (so no one faces this problem again), if the URL is invalid, I'll make it use the default URL, `http://example.com`

**Comment by UnlimitedCookies** [comment] 2020-07-01 22:32
Thank you so much for the troubleshooting!

I still don't quite understand why this option is needed though.

**Comment by Tzahi12345** [comment] 2020-07-01 22:42
There's this Access-Control-Allow-Origin header which becomes a pain to deal with -- basically Chrome won't allow you to access a website where API calls can come from *anywhere*. Chrome (and I think Firefox now too), require servers to tell them which domain the API calls need to be going through.

What this means is, the backend needs to specifically allow your frontend domain (e.g. `ytdl.example.com`), also called the `origin`, to send API requests. This is what the `Access-Control-Allow-Origin` header specifies, *which* domain you will be accessing your backend from. You can check out this [StackOverflow question](https://stackoverflow.com/questions/19743396/cors-cannot-use-wildcard-in-access-control-allow-origin-when-credentials-flag-i) for more details -- you can't just use a wildcard to get around it.

For some reason, this never is an issue on Docker. I think it's because you're always accessing the container locally (even through a reverse proxy), so the header isn't needed. But for non-Docker users, this isn't the case -- unless you're accessing the app through localhost it will be a remote-connection, requiring the Access-Control-Allow-Origin header and thus the correct URL setting.

**Comment by UnlimitedCookies** [comment] 2020-07-01 23:01
Thanks for the comprehensive explanation. I think I do understand now why the `Access-Control-Allow-Origin` header is necessary. I still don't get why it still works when I set it to `http://example.com`, because that's obviously not the front end URL used. But as I could read from your answer, you don't know yourself why it behaves like this on docker 🤷🏻‍♂️


(And it's my bad for not having set a mandatory setting field.)

**Comment by Tzahi12345** [comment] 2020-07-01 23:15
No problem, that header confused me for a while until I got it. And yeah, we're a bit in the dark here as to why it's not needed for Docker. It's a "if it aint broke don't fix it" kinda thing.

I should probably do more validation when saving settings to let users know they have missing fields, it's just a very low priority task so unless it causes issues again, I'll put that one on the backburner. Anyways, I'll close this issue when I get the fix pushed for the missing URL field. Thank *you* for being so helpful in the debug process, glad we caught this bug!

**Comment by UnlimitedCookies** [comment] 2020-07-01 23:19
I'm thankful for your great support efforts!
Now we at least know where to look when someone reports a bug with similar log files ;)

**Comment by Tzahi12345** [comment] 2020-07-02 03:21
All fixed! [See commit here.](https://github.com/Tzahi12345/YoutubeDL-Material/commits/master) Thanks again for the help!

**Closed by Tzahi12345** 2020-07-02 03:21 UTC
Labels: bug
