### ISSUE TITLE
Audio only downloads don't play properly

### ISSUE THREAD

**Issue by chaosay** [Tzahi12345/YoutubeDL-Material#8] opened 2020-02-26 10:17 UTC
Example link: https://www.youtube.com/watch?v=egeMAIXYIvI
Plays fine in VLC, but not with other programs such as quicktime player.
Audacity states that it requires the ffmpeg plugin as it is an uncompressed file.
Alltube handles this link fine.

**Comment by Tzahi12345** [comment] 2020-02-26 21:34
Weird, I was not able to reproduce this bug. Are there any errors that come back from the frontend or backend? I'd like to better understand where it failed here.

**Comment by chaosay** [comment] 2020-02-27 10:45
Sorry, there's no errors at all other than the error message with quicktime player. Everything seems to work it's just delivering an invalid file.

**Comment by LukasK13** [comment] 2020-03-09 20:57
@Tzahi12345 Thanks for this awesome project.
I'm using YoutubeDL-Material in a docker container and can confirm this issue. With [this](https://youtu.be/RacxNskxySo) video I cannot even get it to work in the browser.
When I download the video audio only and click on play, the clip is only one second and has no audio. The downloaded MP3-file is 4.2 MB, so it seems to be fine but nevertheless I am unable to play it using VLC, iTunes, ...
I'm happy to help you digging further into this issue, if you have any idea where to look for errors.

**Comment by Tzahi12345** [comment] 2020-03-10 07:15
@LukasK13 Thanks for the confirmation. Can you verify that no errors appeared in in the backend as well? It's the `node app.js` screen, if you are using Docker it would appear after you run `docker-compose up`.

**Comment by LukasK13** [comment] 2020-03-10 07:22
I can confirm that there are no errors shown in the container logs.

**Comment by Tzahi12345** [comment] 2020-03-10 08:43
Still not able to reproduce, really strange...

Just a thought: maybe it has to do with the youtube-dl version?

The [latest update](https://github.com/Tzahi12345/YoutubeDL-Material/releases/tag/v3.4) (3.4 includes a newer (March 2020) version. Could you try the updated version and see if the error persists?

**Comment by LukasK13** [comment] 2020-03-10 09:27
The problem still exists in the latest update 3.4.
However I digged a little further.
I am running YoutubeDL-Material 3.4 in docker on ubuntu server 19.10. My main machine is a MacBook Pro with MacOS Catalina. As I am not sure if the browser playback and media player playback (VLC, Quicktime, ...), I'm listing both issues separately. 

### Browser Playback
#### MacOS Catalina
- **Safari:** Playback is one second with no audio
- **Firefox:** Playback is working fine 🎉
- **Chrome / MS Edge Chromium:** Playback is working fine 🎉

#### Windows 10
- **Firefox:** Playback is working fine 🎉
- **MS Edge Chromium:** Playback is working fine 🎉

### Playback of downloaded MP3
This is not depending on which browser was used for downloading the audio
#### MacOS Catalina
- **VLC Media Player:** Playback is one second with no audio
- **QuickTime Player:** Playback is 15 seconds with no audio

#### Windows 10
- **VLC Media Player:** Playback is one second with no audio
- **Windows Media Player:** Playback is working fine 🎉

**Comment by Tzahi12345** [comment] 2020-03-10 19:04
I think I see what is happening. The audio file that is downloaded is not actually an mp3, it's either a webm or mkv file that is just *named* as an mp3.

I used a [file analyzer](https://filext.com/online-file-viewer.html) that confirmed by suspicions:

<img src="https://i.imgur.com/Vg0ZwAB.png" height="300">

I'll see if I can get a hotfix out today for it, probably won't take long to fix. I'll close the issue once that's done. Anyways, thanks @LukasK13 for the debugging help! The inconsistent behavior in media players from your testing was really helpful.

**Comment by LukasK13** [comment] 2020-03-10 20:02
Thank you very much for the fast fixing.
I'm glad I could help.

**Comment by Tzahi12345** [comment] 2020-03-10 20:29
No problem! Hotfix is out, just pull the new 3.4 image or download the latest zip from the releases :)

**Closed by Tzahi12345** 2020-03-10 20:29 UTC
Labels: bug
