### ISSUE TITLE
Issue with layout on subscriptions

### ISSUE THREAD

**Issue by Code-Slave** [Tzahi12345/YoutubeDL-Material#88] opened 2020-05-18 14:55 UTC
I am having a layout issue i thing. running docker from latest. screen attached. this is in firefox latest btw on ubuntu 19.10

![Screenshot from 2020-05-18 10-53-24](https://user-images.githubusercontent.com/1482374/82227632-0ca8fe80-98f6-11ea-803f-54d219e11c3e.png)

**Comment by Tzahi12345** [comment] 2020-05-18 15:05
Interesting, I'm not able to reproduce this on Windows w/ Firefox.

If you can use inspect element to see which html element is the problem, that would be helpful. Also, can you go into the browser console to see if there's any errors? Perhaps bootstrap isn't getting loaded for some reason. To get there, right click->inspect element->console.

**Comment by Code-Slave** [comment] 2020-05-18 18:23
ok just odd. Now its working fine. All last night/morning it was like that. I went back in to debug as suggested and now its working. smh

**Comment by Tzahi12345** [comment] 2020-05-18 20:07
Definitely odd. I'll close the issue, but feel free to comment/re-open if it reappears.

**Closed by Tzahi12345** 2020-05-18 20:07 UTC
Labels: bug
